#! /usr/bin/env bash

threads=2
mem_in_gb=2
WorkDir=$CFOUR_SCRATCH

CurrDir=$PWD
export OMP_NUM_THREADS=$threads
#export PATH=$PATH:$Path_to_Cfour

if [ ! -d $WorkDir ]; then
    echo $WorkDir does not exit.
    exit
fi
cd $WorkDir
rm -rf $WorkDir/*

cp $CurrDir/../P4.BASIS $WorkDir/GENBAS
cp $CurrDir/PSIMOS $WorkDir/OLDMOS
touch $WorkDir/JFSGUESS

cat >> ZMAT << EOF
OH
O   0.0   0.0   0.057496044831
H   0.0   0.0  -0.912503955169

*CFOUR(CALC=SCF
REFERENCE=UHF
MULT=2
COORDIANTES=CARTESIAN
SYMMETRY=OFF 
BASIS=SPECIAL,SPHERICAL=ON
MEM_SIZE=$mem_in_gb,MEM_UNIT=GB)

O:P4_PVDZ
H:P4_PVDZ


EOF

xcfour

