#! /usr/bin/env bash

BASIS=$1
PSI_GUESS=$2

if [ -z $BASIS ]; then
    BASIS=STO-3G
fi
echo Basis is $BASIS

if [ ! -z $PSI_GUESS ]; then
    echo Psi-guess
else
    echo Core-guess
fi

GitRoot=../..
threads=2
export OMP_NUM_THREADS=$threads
mem_in_gb=2
CurrDir=$PWD
WorkDir=$CFOUR_SCRATCH

if [ ! -d $WorkDir ]; then
    echo $WorkDir does not exit.
    exit
fi
cd $WorkDir
rm -rf $WorkDir/*

cp $CurrDir/$GitRoot/Cfour/P4.BASIS $WorkDir/GENBAS
if [ ! -z $PSI_GUESS ]; then
    cp $CurrDir/PSIMOS $WorkDir/OLDMOS
    touch $WorkDir/JFSGUESS
fi

cat >> ZMAT << EOF
He5 with four equivalent centers
HE   0.0   0.0   4.0
HE   1.0   2.0   0.0
HE  -1.0   2.0   0.0
HE   1.0  -2.0   0.0
HE  -1.0  -2.0   0.0

*CFOUR(CALC=SCF
COORDINATES=CARTESIAN,UNITS=BOHR
BASIS=SPECIAL,SPHERICAL=ON
REFERENCE=RHF
MEM_SIZE=$mem_in_gb,MEM_UNIT=GB)

HE:P4_$BASIS
HE:P4_$BASIS
HE:P4_$BASIS
HE:P4_$BASIS
HE:P4_$BASIS


EOF

xcfour

cp $WorkDir/OLDMOS $CurrDir/OLDMOS.$BASIS
