#! /usr/bin/env bash

BASIS=$1
PSI_GUESS=$2

if [ -z $BASIS ]; then
    BASIS=STO-3G
fi
echo Basis is $BASIS

if [ ! -z $PSI_GUESS ]; then
    echo Psi-guess
else
    echo Core-guess
fi

GitRoot=../../..
threads=2
export OMP_NUM_THREADS=$threads
mem_in_gb=2
CurrDir=$PWD
WorkDir=$CFOUR_SCRATCH

if [ ! -d $WorkDir ]; then
    echo $WorkDir does not exit.
    exit
fi
cd $WorkDir
rm -rf $WorkDir/*

cp $CurrDir/$GitRoot/Cfour/P4.BASIS $WorkDir/GENBAS
if [ ! -z $PSI_GUESS ]; then
    cp $CurrDir/PSIMOS $WorkDir/OLDMOS
    touch $WorkDir/JFSGUESS
fi

cat >> ZMAT << EOF
H2O
O           -0.005580556816     0.124770196240     0.000000000000
H           -1.409609476816    -1.024054213760     0.000000000000
H            1.498176963184    -0.956139343760     0.000000000000

*CFOUR(CALC=SCF
CHARGE=1,MULT=2
COORDINATES=CARTESIAN,UNITS=BOHR
BASIS=SPECIAL,SPHERICAL=ON
REFERENCE=UHF
MEM_SIZE=$mem_in_gb,MEM_UNIT=GB)

O:P4_$BASIS
H:P4_$BASIS
H:P4_$BASIS


EOF

xcfour

cp $WorkDir/OLDMOS $CurrDir/OLDMOS.UHF.$BASIS

