#! /usr/bin/env bash

threads=2
mem_in_gb=2
WorkDir=$CFOUR_SCRATCH

CurrDir=$PWD
export OMP_NUM_THREADS=$threads
#export PATH=$PATH:$Path_to_Cfour

if [ ! -d $WorkDir ]; then
    echo $WorkDir does not exit.
    exit
fi
cd $WorkDir
rm -rf $WorkDir/*

cp $CurrDir/../../P4.BASIS $WorkDir/GENBAS
#cp $CurrDir/PSIMOS $WorkDir/OLDMOS
#touch $WorkDir/JFSGUESS

BASIS=def2-SV

cat >> ZMAT << EOF
H2O
O           -0.005580556816     0.124770196240     0.000000000000
H           -1.409609476816    -1.024054213760     0.000000000000
H            1.498176963184    -0.956139343760     0.000000000000

*CFOUR(CALC=SCF
COORS=CARTESIAN,UNITS=BOHR
BASIS=SPECIAL,SPHERICAL=ON
REFERENCE=RHF
MEM_SIZE=$mem_in_gb,MEM_UNIT=GB)

O:P4_$BASIS
H:P4_$BASIS
H:P4_$BASIS


EOF

xcfour

cp $WorkDir/OLDMOS $CurrDir/OLDMOS.Cs_$BASIS


