#! /usr/bin/env bash

threads=2
mem_in_gb=2
WorkDir=$CFOUR_SCRATCH

CurrDir=$PWD
export OMP_NUM_THREADS=$threads
#export PATH=$PATH:$Path_to_Cfour

if [ ! -d $WorkDir ]; then
    echo $WorkDir does not exit.
    exit
fi
cd $WorkDir



rm -rf $WorkDir/*

cp $CurrDir/../../P4.BASIS $WorkDir/GENBAS
#cp $CurrDir/PSIMOS $WorkDir/OLDMOS
#touch $WorkDir/JFSGUESS

BASIS=def2-SVP

cat >> ZMAT << EOF
model Cs
H        -1.14356293    -1.24134665     0.75589061
H        -1.14356293    -1.24134665    -0.75589061
HE       -1.81408822     0.52541937     0.00000000
HE        2.38996911     0.09970391     0.00000000

*CFOUR(CALC=SCF
COORDIANTES=CARTESIAN,UNITS=BOHR
BASIS=SPECIAL,SPHERICAL=ON
REFERENCE=RHF
MEM_SIZE=$mem_in_gb,MEM_UNIT=GB)

H:P4_$BASIS
H:P4_$BASIS
HE:P4_$BASIS
HE:P4_$BASIS


EOF

xcfour
#xcfour > runscf.$BASIS
cp $WorkDir/OLDMOS $CurrDir/OLDMOS.$BASIS

