#! /usr/bin/env bash

threads=2
mem_in_gb=2
WorkDir=$CFOUR_SCRATCH

CurrDir=$PWD
export OMP_NUM_THREADS=$threads
#export PATH=$PATH:$Path_to_Cfour

if [ ! -d $WorkDir ]; then
    echo $WorkDir does not exit.
    exit
fi
cd $WorkDir



rm -rf $WorkDir/*

cp $CurrDir/../P4.BASIS $WorkDir/GENBAS
#cp $CurrDir/PSIMOS $WorkDir/OLDMOS
#touch $WorkDir/JFSGUESS

cat >> ZMAT << EOF
linear H2O
O  0.0  0.0  0.0
H  0.0  0.0  0.96
H  0.0  0.0 -0.96

*CFOUR(CALC=SCF
COORDIANTES=CARTESIAN
SUBGROUP=0
BASIS=SPECIAL,SPHERICAL=ON
REFERENCE=RHF
MEM_SIZE=$mem_in_gb,MEM_UNIT=GB)

O:P4_PVDZ
H:STO-3G
H:STO-3G


EOF

xcfour

